- .eslintrc
- .travis.yml
- package.json
- test/test.js
Technically, this only fixes part of the problem since somebody with better permissions than I will need to enable Travis-CI for this repo.
Plus, ESLint is failing for me locally, so we'll probably need to resolve the 4 errors in a future PR.
```
/Users/pdehaan/dev/github/mozilla/fathom/test/test.js
45:14  error  'piecesOfTheReadabilityTestCase' is defined but never used  no-unused-vars
73:54  error  'isBlock' is not defined                                    no-undef
92:18  error  'paragraphish' is defined but never used                    no-unused-vars
103:15  error  'kb' is defined but never used                              no-unused-vars
✖ 4 problems (4 errors, 0 warnings)
```
Fixes #6
> Add initial .travis.yml file

- .eslintrc
- index.js
- utils.js
Despite `for (const blah of whatever)` being perfectly legal according to spec, Firefox throws a syntax error. Sucky
This looks like it might be the bug? https://bugzilla.mozilla.org/show_bug.cgi?id=1094995
> Replace for const... with let for Firefox compat

- README.md
> Add missing comma in README example

- .gitignore
- index.js
- package.json
- rollup.config.js
I wanted to use fathom in a webextension, but didn't want to bother setting up webpack or another module bundler. So I threw together a quick [Rollup](https://rollupjs.org/) config to build a single `fathom.js` file using UMD. When dropped in a webpage, it should add a `fathom` global with all the exports from the library on it. After installing the dev dependencies, you can run it with `./node_modules/.bin/rollup -c`.
I made a minor attempt at seeing if I could run the test suite against it, and failed; mocha seems to error out with the message: `Cannot read property 'regeneratorRuntime' of undefined`, referring to a reference to `global.regeneratorRuntime`. I think it has something to do with how [wu.js](https://github.com/fitzgen/wu.js/) is Webpacked, but I'm not really sure.
I tested …
> Add rollup config for creating a single-file build of Fathom.

- cli/fathom_web/list.py
- cli/setup.py
Addresses #97 
This PR adds a command line tool to aid in vectorization. You can list the files in a directory for easy copy-pasting into the vectorizer box in Fathom-Fox. Optionally, you can save the output to a file so you can reference the file later and forgo using this tool every time.
> Adds commandline tool to list filenames for vectorization and optionally save to a file

- cli/fathom_web/train.py
Addresses #104 
Previously, `accuracy_per_tag()` ran each sample through the model one at a time and then checked the accuracy for that sample. This pull request runs all the samples through the model at the same time and then computes the accuracy metrics for all the samples using numpy methods.
There is an additional change to `accuracy_per_tag()` such that it now takes predictions as an argument instead of the model and the samples. This is because the main source of calls for `accuracy_per_tag()` is `learn()` which itself runs all the samples through the model and therefore has the predictions laying around for use. This change requires the last calls to `accuracy_per_tag()`, located within `main()`, to run the samples through the model beforehand.
The new overall profile shows that …
> Accuracy per tag optimization

- trainees.js
Remove bound-ruleset caching. The caching was to speed in-browser training, which is now deprecated in favor of the CLI fathom-train.
It may still be illuminating to go chase this down properly, as it may represent a latent bug in Fathom's own caching, but the important thing for now is to make the user-facing tools work.
> Make BAD labeling reliable. Fix #98.

- cli/fathom_web/commands/train.py
This will both enhance convenience and mean new users don't fail to notice some very useful output (which is what happened as I was bringing Bianca and Daniel up to speed with 3.0).
> Make verbosity the default in fathom-train. Fix #108.

- docs/ruleset.rst
- docs/using.rst
- rule.mjs
- test/demos.mjs
- test/lhs_tests.mjs
- test/ruleset_tests.mjs
- test/utils_tests.mjs
Addresses #51.
Allows users to omit the explicit call to `out()` when specifying their output rules. Users can now simply use the key string as the RHS of the rule. For example: `rule(type('titley').max(), out('title'))` can now be written as `rule(type('titley').max(), 'title')`.
> Out rule simplification

- cli/fathom_web/commands/extract.py
- cli/fathom_web/commands/pick.py
- cli/fathom_web/test/test_pick.py
Addresses #125 
This PR changes `fathom-pick` such that it specifically moves HTML files and any extracted resources. Now that samples will almost certainly have an associated directory of extracted resources, we need to move those resources along with the HTML files when dividing samples into training/validation/test so the references to the resources in the HTML still work.
> Move resources with pick

- .eslintrc.yml
- test/demos.mjs
- test/lhs_tests.mjs
- test/ruleset_tests.mjs
- test/utils_tests.mjs
- utilsForFrontend.mjs
The width and height properties in the return value from getComputedStyle are of the form '*px'.
> Fix #118: Improve `isVisible` for correctness and performance

- cli/fathom_web/commands/extract.py
- cli/fathom_web/test/test_extract.py
I ran into a page in my "other-web" corpus that contained percent encoded `=`'s at the end for the padding characters. `fathom-extract` did not like that. This PR adds support for such strings.
> Adds decode() method, updates regex, and adds tests

- utilsForFrontend.mjs
This fixes the error in the Docs deployment stage that TravisCI runs on merges to 'master' resulting from changes in PR #129.
> Move istanbul ignore comments

- cli/fathom_web/commands/extract.py
- cli/fathom_web/test/test_extract.py
I encountered frozen pages with unpadded base64 strings. Python's `base64.b64decode()` method requires padded strings, so this PR pads strings that are unpadded.
@biancadanforth: You may need this for your samples.
> Updates decode to work on unpadded base64 strings

- .gitignore
- cli/fathom_web/commands/label.py
- cli/fathom_web/test/test_label.py
- cli/setup.py
* This is largely based off of the 'fathom-extract' CLI.
* This tool handles documents with multiple 'html' elements by capturing each original opening html tag and each modified opening html tag in a list of tuples and iterating through each tuple to 'string.replace' to update the HTML document.
* I originally had a test that asserted that '< html >' became '< html data-fathom="test" >', but I discovered that this isn't valid HTML per the [specification](https://www.w3.org/TR/html53/syntax.html#start-tags)
* Similarly, there is no test for comments inside an 'html' tag, because that is also invalid HTML.
Open question: Is `fathom-label` descriptive enough? This tool only labels an entire page, so perhaps we can be more specific. Suggestions welcome!
> Fix #138: Add fathom-label CLI

- docs/training.rst
Referencing https://github.com/mozilla/fathom-trainees/pull/9, the docs should be updated to say hard link, as soft links do not work in this situation.
> Replace symlink with hard link in Training section of docs

- cli/fathom_web/commands/list.py
- cli/fathom_web/test/test_list.py
This PR makes `fathom-list` a specialized tool for FathomFox. I have found that I have needed to do a significant amount of work to create the filename lists I needed for vectorization, so I'm proposing `fathom-list` do all this work for us.
It is likely that training samples are not all in the same directory. You may the following directory structure (which is what we're currently recommending):
```
samples/
|-  training/
|    |-  source_a/
|    |    |-  positive/
|    |    |    |-  [lots of html files]
|    |    |-  negative/
|    |    |    |-  [lots of html files]
|    |-  source_b/
|    |    |-  positive/
|    |    |    |-  [lots of html files]
|    |    |-  negative/
|    |    |    |-  [lots of html files]
```
In this case, using `fathom-list` is not convenient for getting your …
> Make `fathom list` a specialized tool for FathomFox

- cli/fathom_web/accuracy.py
- cli/fathom_web/commands/train.py
As the title suggests, this PR adds 95% confidence intervals to the output of the false positive and false negative metrics computed by fathom-train.
> Adds confidence intervals for false positives and false negatives

- cli/fathom_web/commands/serve.py
Fix timeouts when vectorizing: https://github.com/mozilla/fathom-fox/issues/67.
For whatever reason, fathom-serve spits out errors like this while serving rapid-fire vectorization requests:
```
File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 414, in handle_one_request
method()
File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 653, in do_GET
self.copyfile(f, self.wfile)
File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 844, in copyfile
shutil.copyfileobj(source, outputfile)
File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 82, in copyfileobj …
```
> Make `fathom-serve` multithreaded.

- cli/fathom_web/commands/extract.py
Before, it was emitting resource filenames like '34None'. Now it asks the user and remembers the answer (though you should add them to the dict by hand at the end of the run as well).
Also added some webby types (from an MDN page) that guess_extension() didn't know.
> Teach fathom-extract to deal with unknown MIME types.

- cli/fathom_web/commands/train.py
This PR adds a sample weighting factor to balance the importance of positive samples with negative samples. See: https://pytorch.org/docs/stable/nn.html#bcewithlogitsloss
The main question is will we always want this? I think yes as a default, but it can always be made optional at a later date if need be.
> Adds automatic sample weighting

- cli/fathom_web/commands/list.py
I needed this a second time, so I guess it's time to make it publicly available!
Specifically, I'm using it to tell which domains were assigned to Vlad and actually yielded a sample, so I don't assign him the same domain a second time.
> Teach fathom-list how to optionally spit out original URLs of samples.

- cli/fathom_web/test/test_list.py
I'm inclined not to pin the versions in CI, as it does currently give us an early warning of the breakage people might see if they `pip install fathom-web`.
> Click apparently changed the kind of quotes it uses.

- cli/fathom_web/accuracy.py
- cli/fathom_web/commands/test.py
- cli/fathom_web/commands/train.py
Convert the per-page table into a per-tag one. This should help us chase down failures better. This needs the FathomFox branch of the same name if you want to see the markup snippets in the table.
> Per tag report

- cli/fathom_web/commands/train.py
The line `all_pages = training_data['pages']` does not make a copy of `training_data['pages']`, so when `extend()` is called on it, the dictionary entry in `training_data` is changed.
> Fixes bug that printed validation per-tag results as part of training per-tag results

- cli/fathom_web/accuracy.py
FathomFox collects them in parallel, so the order is a bit mixed up each run. It makes reports hard to compare.
> Sort per-tag reports by filename so they don't come out in random order.

- .travis.yml
I think we were testing it because one of us was running it. I don't think we are anymore. And besides, 3.8 is out.
> Drop Python 3.6 testing.

- cli/fathom_web/accuracy.py
- cli/fathom_web/commands/test.py
- cli/fathom_web/commands/train.py
Adds a decision threshold option to `fathom-train` and an argument to `fathom-test`. I added it as an argument to `fathom-test` so the user will be less inclined to forget they used some custom threshold in train.
> Add ability to tune decision threshold

- docs/ruleset.rst
- index.mjs
- lhs.mjs
- ruleset.mjs
- test/ruleset_tests.mjs
Considered making a workalike to `dom()` called `element()` or `one()` (and aliasing `dom()` to `all()`), but then you'd need to change a ruleset every time you wanted to use it differently. That should be the application's decision, not the ruleset writer's. And, of immediate practical value, any ruleset using `element()` in production would need a clumsy switch to use `dom()` in training.
> Add `againstElement()`, which lets us efficiently classify only a single element.

- cli/fathom_web/commands/train.py
Without doing this, the vector files are opened with the CP1252 encoding on Windows, and the trainer will not work.
> Tells the trainer to use assume a utf-8 encoding for vector files.

- cli/fathom_web/utils.py
I noticed this while doing #227. The [docs](https://docs.python.org/3/reference/compound_stmts.html#function-definitions) frown upon using mutable objects as default arguments because they can inadvertently be changed for future function calls.
> Changes default arg from [] to None and adds explicit check.

- cli/Makefile
- docs/Makefile
Calling just `pytest` doesn't appear to find the correct pytest, even when PATH is explicitly exported. (I deduce this from the fact that it doesn't see the libs installed in the venv.) However, executing a shell script that prints out $PATH shows that PATH did get passed down to the subshell. If I explicitly set the env var PATH, it works.
> Use an in-project venv for cli every time. Fix #225.

- cli/fathom_web/vectorizer.py
- docs/Makefile
I do run into an error every time during vectorization though. Regardless of how many samples, threads, delay, I always hit a `Error: can't access property "browser", tab is null` during vectorization. I don't think I've hit this before. I want to get this over to @erikrose to see if the changes I made to get autovec working on Windows cause the same problems on Mac.
> Adds changes needed to get vectorization to "work" on Windows.

- cli/fathom_web/accuracy.py
Casting objects feels bad to me. I think it's because I assume it points to some other problem, but this also seems a simple way to avoid the potential problem.
> Cast ints to floats in MCC computation to avoid potential integer overflows

- cli/fathom_web/accuracy.py
- cli/fathom_web/commands/train.py
These counting errors regarding pruned elements caused incorrect metrics. In `accuracy.py`, `num_prunes` gets double counted for `false_negatives` since it is already added to `number_of_tags` on the previous line. In the calls to `pretty_accuracy()` in `train.py`, `num_yes` already has the number of pruned elements added to it in `tensors_from()`, so we should not add `num_prunes` to it in the function call.
> Fix counting errors in metrics due to double counting pruned elements.

- cli/fathom_web/vectorizer.py
Without this option, FathomFox source doesn't show up in the debugger on Windows.
> Turn on profile option needed for FathomFox debugging on Windows

- cli/fathom_web/vectorizer.py
- fathom_fox/addon/vector.js
This is a bandage solution for #256. Any duplicated feature vectors get removed at the same time that the file hashes are added to the header after vectorization. Any qualms with this being an in-place operation? As I stated in the linked issue, I will solve the problem more appropriately after the initial form autofill effort is completed.
> Fixing duplicated vectors in a post-processing step.
